/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalCenterRouteImport } from './routes/legal-center'
import { Route as LegalCenterIndexRouteImport } from './routes/legal-center/index'
import { Route as LegalCenterNoticesRouteImport } from './routes/legal-center/notices'
import { Route as LegalCenterPrivacyRouteImport } from './routes/legal-center/privacy'
import { Route as LegalCenterTermsRouteImport } from './routes/legal-center/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCenterRoute = LegalCenterRouteImport.update({
  id: '/legal-center',
  path: '/legal-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCenterIndexRoute = LegalCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalCenterRoute,
} as any)
const LegalCenterNoticesRoute = LegalCenterNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => LegalCenterRoute,
} as any)
const LegalCenterPrivacyRoute = LegalCenterPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalCenterRoute,
} as any)
const LegalCenterTermsRoute = LegalCenterTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalCenterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal-center': typeof LegalCenterRouteWithChildren
  '/legal-center/notices': typeof LegalCenterNoticesRoute
  '/legal-center/privacy': typeof LegalCenterPrivacyRoute
  '/legal-center/terms': typeof LegalCenterTermsRoute
  '/legal-center/': typeof LegalCenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal-center/notices': typeof LegalCenterNoticesRoute
  '/legal-center/privacy': typeof LegalCenterPrivacyRoute
  '/legal-center/terms': typeof LegalCenterTermsRoute
  '/legal-center': typeof LegalCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal-center': typeof LegalCenterRouteWithChildren
  '/legal-center/notices': typeof LegalCenterNoticesRoute
  '/legal-center/privacy': typeof LegalCenterPrivacyRoute
  '/legal-center/terms': typeof LegalCenterTermsRoute
  '/legal-center/': typeof LegalCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/legal-center'
    | '/legal-center/notices'
    | '/legal-center/privacy'
    | '/legal-center/terms'
    | '/legal-center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/legal-center/notices'
    | '/legal-center/privacy'
    | '/legal-center/terms'
    | '/legal-center'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/legal-center'
    | '/legal-center/notices'
    | '/legal-center/privacy'
    | '/legal-center/terms'
    | '/legal-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LegalCenterRoute: typeof LegalCenterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-center': {
      id: '/legal-center'
      path: '/legal-center'
      fullPath: '/legal-center'
      preLoaderRoute: typeof LegalCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-center/': {
      id: '/legal-center/'
      path: '/'
      fullPath: '/legal-center/'
      preLoaderRoute: typeof LegalCenterIndexRouteImport
      parentRoute: typeof LegalCenterRoute
    }
    '/legal-center/notices': {
      id: '/legal-center/notices'
      path: '/notices'
      fullPath: '/legal-center/notices'
      preLoaderRoute: typeof LegalCenterNoticesRouteImport
      parentRoute: typeof LegalCenterRoute
    }
    '/legal-center/privacy': {
      id: '/legal-center/privacy'
      path: '/privacy'
      fullPath: '/legal-center/privacy'
      preLoaderRoute: typeof LegalCenterPrivacyRouteImport
      parentRoute: typeof LegalCenterRoute
    }
    '/legal-center/terms': {
      id: '/legal-center/terms'
      path: '/terms'
      fullPath: '/legal-center/terms'
      preLoaderRoute: typeof LegalCenterTermsRouteImport
      parentRoute: typeof LegalCenterRoute
    }
  }
}

interface LegalCenterRouteChildren {
  LegalCenterNoticesRoute: typeof LegalCenterNoticesRoute
  LegalCenterPrivacyRoute: typeof LegalCenterPrivacyRoute
  LegalCenterTermsRoute: typeof LegalCenterTermsRoute
  LegalCenterIndexRoute: typeof LegalCenterIndexRoute
}

const LegalCenterRouteChildren: LegalCenterRouteChildren = {
  LegalCenterNoticesRoute: LegalCenterNoticesRoute,
  LegalCenterPrivacyRoute: LegalCenterPrivacyRoute,
  LegalCenterTermsRoute: LegalCenterTermsRoute,
  LegalCenterIndexRoute: LegalCenterIndexRoute,
}

const LegalCenterRouteWithChildren = LegalCenterRoute._addFileChildren(
  LegalCenterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LegalCenterRoute: LegalCenterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
